{
 "title": "HTTP Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(http_server_requests_seconds_count, application)"
   },
   {
    "name": "instance",
    "query": "label_values(http_server_requests_seconds_count{application=~\"$service\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$service\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$service\", instance=~\"$instance\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=~\"$service\", instance=~\"$instance\"}[1m]) / rate(http_server_requests_seconds_count{application=~\"$service\", instance=~\"$instance\"}[1m])",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$service\", instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Top Endpoints by Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_server_requests_seconds_count{application=~\"$service\", instance=~\"$instance\"}[1m])) by (uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "500",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(rate(http_server_requests_seconds_count{\n    status=~\"5..\",\n    application=~\"$service\",\n    instance=~\"$instance\"\n  }[1m])) by (uri)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Endpoints (P95 by URI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$service\", instance=~\"$instance\"}[1m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}