{
 "title": "Pharma Logs Monitoring",
 "tags": [
  "loki",
  "logs",
  "spring-boot"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "container", "query": "label_values(container_name)" },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate (logs)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate({job=\"docker-logs\"} |= \"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate({job=\"docker-logs\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Logs (Live)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{job=\"docker-logs\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "500 Errors",
   "type": "logs",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{job=\"docker-logs\"} |= \"500\""
    }
   ]
  },
  {
   "title": "Exceptions / Stacktrace",
   "type": "logs",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{job=\"docker-logs\"} |= \"Exception\""
    }
   ]
  },
  {
   "title": "Search Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 28, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{job=\"docker-logs\"} |= \"$search\""
    }
   ]
  }
 ]
}